#! /usr/bin/env php
<?php
require_once dirname(__FILE__).'/common.php';
require_once dirname(__FILE__).'/config.php';

/*
extract from F2ban logs the banned IP
use whois query to determine the range of provider IP
ban the subnet printing range ip in hosts.deny format
*/

/*
TODO:
- use PHP7
- use file cache instead of APC
*/

/* @see config.php
// abstraction representing the configuration of this instance
class Config {
    // countries that will be banned
    public static function getBannedCountries(){
        return ['CN','VN','KR','IN','HK','TH','TW','SC','NP'];
    }
    // first 3 digits of IP classes that will be skipped
    public static function getIPWhiteList() {
        return [
        "192.",
        ];
    }
}*/

// parsa il log e trova gli ip banned
function parse_log($file_cont) {
    if( empty($file_cont) ) {
        return ;
    }
    $a_lines = explode( "\n", $file_cont);
    foreach($a_lines as $line){
        // 2014-03-28 01:56:31,793 fail2ban.actions: WARNING [ssh] Ban 212.83.175.89
        $m = preg_match('/Ban ([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})/', $line, $matches, PREG_OFFSET_CAPTURE);
        if( 0 !== $m ) {
            $ip = implode('.', [
                $matches[1][0],
                $matches[2][0],
                $matches[3][0],
                $matches[4][0]
                ] );

            //echo "$line \n";
            // echo sprintf( "# %s %s \n", $ip, get_country($ip) );
            IPList::add($ip);
        }
    }
}


//------------------------------------------------------------------------------
// cache routines
//------------------------------------------------------------------------------
/*
class Cache {
    public static function exists($k){ return apc_exists($k); }
    public static function fetch($k){ return apc_fetch($k); }
    public static function store($k, $str, $ttl){ return apc_store( $k, $str, $ttl); }
    public static function add($k, $str, $ttl){ return self::store( $k, $str, $ttl); }
}
*/
class Cache {
    public static function exists($k){ return MFCache::fetch($k) !== false; }
    public static function fetch($k){ return MFCache::fetch($k); }
    public static function store($k, $str, $ttl=''){ return MFCache::store( $k, $str, $ttl); }
    public static function add($k, $str, $ttl){ return self::store( $k, $str, $ttl); }
}

// save and read data, will last in cache 1 gg
class MFCache {
    static $data = [];
    public static function fetch($cache_key) {
        $path = self::getFileName();
        if( !file_exists($path) ) {
            return false;
        }
        if( empty(self::$data) ) {
            self::$data = unserialize( file_get_contents($path) );
        }
        return isset(self::$data[$cache_key]) ? self::$data[ $cache_key ] : false;
    }
    public static function store($cache_key, $val, $ttl_secs=3600 ) {
        self::$data[$cache_key] = $val;
        $path = self::getFileName($cache_key);
        file_put_contents($path, serialize(self::$data) );
    }
    public static $cache_dir = __DIR__;
    public static $cache_date_fmt = 'Ymd';
    // ottiene il filename.  la cache dura tutta la giornata
    public static function getFileName( ) {
        $f = sprintf('%s/cache/%s_%s.txt', self::$cache_dir,
            $name=basename(__FILE__) ,
            date(self::$cache_date_fmt) );
        return $f;
    }
    // eliminare i file più vecchi di 1 giorno
    public static function cleanup() {
        $files = glob(self::$cache_dir."/cache/*");
        $time  = time();
        $s_day = 60*60*24;
        foreach ($files as $file){
            if (is_file($file)){
                if ($time - filemtime($file) >= $s_day*2) {// 2 days
                    unlink($file);
                }
            }
        }
    }
}
MFCache::cleanup();
// MFCache::store( $k='aa', $str=111);
// $v = MFCache::fetch( $k);

/*
// abstraction on cache engines available
ini_set('apc.enable_cli',1);
if (!function_exists('apc_fetch')) {
    function apc_fetch($key) {
        return apcu_fetch($key);
    }
    function apc_exists($keys) {
        return apcu_exists($keys);
    }
    function apc_delete($key) {
        return apcu_delete($key);
    }
    function apc_store($key, $var, $ttl) {
        return apcu_store($key, $var, $ttl);
    }
    function apc_inc($key, $step = 1) {
        return apcu_inc($key, $step);
    }
    function apc_cache_info($cache_type = "", $limited = false) {return apcu_cache_info($limited);}

    function apc_clear_cache() {return apcu_clear_cache();}
}
if(!function_exists('apc_exists')) {
    function apc_exists($keys) {
        $result = false;
        $v = apc_fetch($keys, $result);
        return $result;
    }
}*/

//------------------------------------------------------------------------------


class Whois {

/* ANOMALO:
[ is restricted to network administration purposes. For further information,  ]
[ use 'whois -h whois.nic.ad.jp help'. To only display English output,        ]
[ add '/e' at the end of command, e.g. 'whois -h whois.nic.ad.jp xxx/e'.      ]

No match!!

Reference: WHOIS servers of RIRs
  APNIC WHOIS(whois.apnic.net)
  ARIN WHOIS(whois.arin.net)
  RIPE WHOIS(whois.ripe.net)
  LACNIC WHOIS(whois.lacnic.net)
  AfriNIC WHOIS(whois.afrinic.net)
*/
    // cached whois
    // ritorna str vuota se non trova info
    public static function get_whois($ip) {
        if( Cache::exists($ip) ) {
            echo "\n"."# whois from cache ".time()."\n";
            return Cache::fetch($ip);
        } else {
            $str = `whois $ip`;
            Cache::add( $ip, $str, $ttl=60*60*2 );
            return trim($str);
        }
    }
    // TODO: quando non è possibile determinare la country dall'output di whois
    // usa geoIP
    public static function get_country($ip) {
        $str = self::get_whois($ip);
        $a_lines = explode( "\n", $str);
        foreach($a_lines as $line  ){
            //"country:        TR"
            if( strpos($line, 'country:') !== false ) {
                $s = str_replace('country:','',$line);
                $s = trim($s);
                return $s;
            }
        }
        // usa metodi alternativi per ottenere la country!
        return self::get_WS_country($ip);
    }

    // ottiene country da servizio alternativo
    /*
    GeoIP
        apt-get install geoip-database
    PHP geoip
        /etc/php5/mods-available/geoip.ini
    Cloud API:
        curl -sS ipinfo.io
    */
    public static function get_WS_country($ip){
        // ip es. 43.255.190.116
        /*{
        "ip": "43.255.190.116",
        "hostname": "No Hostname",
        "city": null,
        "country": "HK",
        "loc": "22.2500,114.1667"
        }*/

        if( Cache::exists($ip) ) {
            echo "\n"."# whois from cache ".time()."\n";
            $json = Cache::fetch($ip);
        } else {
            $cmd = "curl -sS ipinfo.io/$ip";
            echo "# $cmd \n";
            $json = `$cmd`;
            $json = trim($json);
            Cache::add( $ip, $json, $ttl=60*60*2 );
        }


        try {
            $a = json_decode($json, $assoc=true);
            if( empty($a) ) {
                return '';
            }
            return $a["country"];
        } catch (Exception $e) {
            $fmt = 'Exception: <b>%s</b> line:%s file:%s<br> trace:<pre>%s</pre>';
            $msg = sprintf($fmt, $e->getMessage(),$e->getFile(), $e->getLine(), $e->getTraceAsString() );
            echo "# $msg";
        }
        return '';
    }

    /*
sudo geoip-database-contrib_update
geoiplookup 211.216.48.205
GeoIP Country Edition: KR, Korea, Republic of
GeoIP City Edition, Rev 1: KR, N/A, N/A, N/A, N/A, 37.570000, 126.980003, 0, 0
GeoIP ASNum Edition: AS4766 Korea Telecom
    */
    public static function get_DB_country($ip){
        $txt = `/usr/bin/geoiplookup $ip`;
        // returns 1 pattern matches, 0 if not, FALSE if an error
        $num_matches = preg_match('/^GeoIP Country Edition: (.*),(.*)$/', $txt, $a_matches, PREG_OFFSET_CAPTURE);
        if(false === $num_matches) {
            $a_pcre_err=array_flip(get_defined_constants(true)['pcre']);
            die( preg_last_error() /*.' '.$a_pcre_err[preg_last_error()]*/ );
        } elseif($num_matches===0) {
            // no matches
            return '';
        } else {
            // ok

            // echo '<pre>',var_dump( $a_matches ),'</pre>'; // DEBUG
            // die(__FUNCTION__.' '.__FILE__.' '.__LINE__);
            return $a_matches[1];
        }
    }


    // TODO: nel caso non sia possibile recuperare un inetnum perché whois non
    // ha il formato canonico es.  43.255.190.116
    // ritorna un range di sintesi
    public static function get_inetnum($ip) {
        $str = self::get_whois($ip);
        if( !empty($str) ) {
            $a_lines = explode("\n", $str);
            foreach($a_lines as $line  ){
                // "inetnum:        85.25.203.255 - 85.25.203.255"
                if( strpos($line, 'inetnum:') !== false ) {
                    $s = str_replace('inetnum:','',$line);
                    $s = trim($s);
                    return $s;
                }
            }
        }
        return self::build_inetnum($ip);
    }
    // TODO: nel caso non sia possibile recuperare un inetnum perché whois non
    // ha il formato canonico es.  43.255.190.116
    // ritorna un range di sintesi
    public static function build_inetnum($ip){
        $a_ip = explode( '.', trim($ip) );
        $ip_1 = sprintf('%s.%s.%s.%s', $a_ip[0], $a_ip[1], $a_ip[2], '0');
        $ip_2 = sprintf('%s.%s.%s.%s', $a_ip[0], $a_ip[1], $a_ip[2], '255');
        return sprintf("%s - %s", $ip_1,$ip_2);
    }
}

class TCPWrappers {
    public static function count_deny($ip){
        // non prendo tutto l'ip, ma solo la prima parte
        // non uso cache perchè il file varia mentre sto analizzando il log
        $a=explode( '.', $ip);
        $part_ip = implode('.', [$a[0],$a[1]] );
        $cmd = "grep $part_ip /etc/hosts.deny | wc -l";
        // echo "$cmd \n";
        $count = `$cmd`;
        return trim($count);
    }

    public static function getDenyCount($ip){
        // non prendo tutto l'ip, ma solo la prima parte
        // non uso cache perchè il file varia mentre sto analizzando il log
        $a=explode( '.', $ip);
        $part_ip = implode('.', [$a[0],$a[1]] );
        $cmd = "grep 'ALL: $part_ip' /etc/hosts.deny ";
        // echo "$cmd \n";
        $count = `$cmd`;
        return trim($count);
    }
    // inetnum = "202.109.128.0 - 202.109.191.255"
    public static function getFormattedFromInetNum($inetnum) {
        if( empty($inetnum) ) {
            return '';
        }
        $a_ip = explode('-',trim($inetnum));
        $s = '';
        foreach(self::rangeFromIP($a_ip[0], $a_ip[1]) as $i=>$ip ){
            $s .= sprintf("ALL: %s \n", trim($ip) );
        }
        return $s;
    }

    // dati due ip 202.109.128.0, 202.109.191.255, sviluppa un range
    public static function rangeFromIP($ip_1, $ip_2) {
        $a_ip_1 = explode('.', $ip_1);
        $a_ip_2 = explode('.', $ip_2);

        $i_ip_1 = ip2long($ip_1);
        $i_ip_2 = ip2long($ip_2);
        // @see long2ip

        //return [$ip_1, $ip_2];
        $a = [];
        for( $i=$a_ip_1[2]; $i <= $a_ip_2[2]; $i++){
            $a[]="{$a_ip_1[0]}.{$a_ip_1[1]}.$i.";
        }
        return $a;
    }

}


// raccoglie gli ip e recupera info
class IPList {
    static $list=[];
    public static function getAll(){
        ksort(self::$list);
        return self::$list;
    }
    public static function add($ip){

        if( array_key_exists($ip, self::$list ) ){
            self::$list[ $ip ][ 'ban_count' ]++;
        } else {
            self::$list[ $ip ] = [
                'ban_count' => 1,
                'country'   => whois::get_country($ip),
                'inetnum'   => whois::get_inetnum($ip),
                'tcpwrap_denied' => TCPWrappers::count_deny($ip)
            ];
        }
    }
}

function is_in_whitelist($ip){
    $a_whitelist = Config::getIPWhiteList();
    $ip_beg = substr($ip,0,3);
    return in_array($ip_beg,$a_whitelist);
}




//-----------------------------------------------------------------------------------
//  actions
//-----------------------------------------------------------------------------------

//
function action_main($only_missing=false) {
    // parsa il log e trova gli ip banned
    foreach( ['/var/log/fail2ban.log','/var/log/fail2ban.log.1'] as $logfile){
        $file_cont = file_get_contents($logfile);
        parse_log($file_cont);
    }

    // stampa lista ip e info
    $a_banned = IPList::getAll();
    foreach($a_banned as $ip => $a_ip_info){
        $padded_ip = str_pad($ip, 16, ' ', STR_PAD_RIGHT);
        $padded_count = str_pad($a_ip_info['ban_count'], 3, ' ', STR_PAD_RIGHT);


        $deny_lines = TCPWrappers::getDenyCount($ip);
        // due possibili aoutput, aoutput esteso per controllo manuale o solo ip da aggiungere al hosts.deny
        if( !$only_missing ) {
            echo sprintf("#ip:%s country:%s bancount:%s tcpwrap_denied:%s inet:%s \n",
                $padded_ip,
                $a_ip_info['country'],
                $padded_count,
                $a_ip_info['tcpwrap_denied'],
                $a_ip_info['inetnum']
                );

            if( !empty($deny_lines) ) {
                echo "#in hosts.deny:\n";
                echo $deny_lines;
                echo "\n\n";
            } else {
                echo "# NOT in hosts.deny!\n";
                $a_banned_countries = Config::getBannedCountries();
                $country = strtoupper(trim($a_ip_info['country']));
                if( in_array($country, $a_banned_countries) ) {
                    echo TCPWrappers::getFormattedFromInetNum($a_ip_info['inetnum']);
                } else {
                    echo sprintf("# skipping non %s: %s \n", implode(',',$a_banned_countries), $a_ip_info['country']);
                }
            }
        } else {
            if( empty($deny_lines) ) {
                echo TCPWrappers::getFormattedFromInetNum($a_ip_info['inetnum']);
            }
        }
    }
}



function action_test() {
    //dati due ip 202.109.128.0, 202.109.191.255, sviluppa un range
    $ip_1 = '202.109.128.0';
    $ip_2 = '202.109.191.255';
    $a = TCPWrappers::rangeFromIP($ip_1, $ip_2);
    echo '<pre>',var_dump( $a ),'</pre>'; // DEBUG
    die(__FUNCTION__.__FILE__);
}


function action_usage($argv){
  return <<<__END__
uso:
    {$argv[0]} [test print main]
uso del programma
__END__;
}
//------------------------------------------------------------------------------
//  main
//------------------------------------------------------------------------------
if( PHP_SAPI !== 'cli'){
    die('cli script');
}

$action = isset($argv[1]) ? $argv[1] : 'main';

switch($action) {

    case 'test':
        action_test();
    break;

    case 'print':
        echo "# stampa IP da bannare \n";
        action_main(true);
    break;

    case 'main':
    default:
        //die(action_usage());
        action_main(false);
    break;
}



